framework:
  rate_limiter:
    admin_invite:
      policy: fixed_window
      limit: 20
      interval: '1 hour'
    invite_activation:
      policy: fixed_window
      limit: 15
      interval: '1 hour'
    cv_contact:
      policy: fixed_window
      limit: 8
      interval: '1 hour'
    setup_totp:
      policy: sliding_window
      limit: 5
      interval: '15 minutes'
    login_totp:
      policy: sliding_window
      limit: 5
      interval: '5 minutes'
