#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * @brief Concatenate static CV public stylesheets into a single cache-friendly bundle.
 *
 * Usage: php tools/build-cv-public-css-bundle.php
 *
 * @date 2026-06-21
 * @author Stephane H.
 */

$projectDir = dirname(__DIR__);
$cssDir = $projectDir.'/public/css';
$outputPath = $cssDir.'/cv-public-static-bundle.css';

/** @var list<string> */
$sourceFiles = [
    'cv-public-layout.css',
    'cv-about-public.css',
    'cv-public-sections.css',
    'cv-experience.css',
    'cv-education.css',
    'cv-certification.css',
    'cv-languages.css',
    'cv-interests.css',
    'cv-web-profiles.css',
    'cv-references.css',
    'cv-contact-modal.css',
    'cv-pencil-decor.css',
];

$buffer = "/* Auto-generated by tools/build-cv-public-css-bundle.php — do not edit manually */\n";

foreach ($sourceFiles as $filename) {
    $absolutePath = $cssDir.'/'.$filename;
    if (!is_file($absolutePath)) {
        fwrite(STDERR, "Missing source file: {$absolutePath}\n");
        exit(1);
    }

    $buffer .= "\n/* --- {$filename} --- */\n";
    $buffer .= (string) file_get_contents($absolutePath);
    $buffer .= "\n";
}

if (file_put_contents($outputPath, $buffer) === false) {
    fwrite(STDERR, "Unable to write bundle: {$outputPath}\n");
    exit(1);
}

fwrite(STDOUT, "Wrote {$outputPath} (".strlen($buffer)." bytes)\n");
